export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS';
export const LOGIN_REQUEST_FAIL = 'LOGIN_REQUEST_FAIL';

export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER';

export const LOG_OUT_USER = 'LOG_OUT_USER';
